// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generated sidebars — Docusaurus reads the folder structure
  // and _category_.json files to build the navigation automatically.
  // Just add/remove files and folders; no manual updates needed.

  scriptsSidebar: [
    {
      type: "autogenerated",
      dirName: "scripts-and-source",
    },
  ],

  postMortemsSidebar: [
    {
      type: "autogenerated",
      dirName: "post-mortems",
    },
  ],

  librarySidebar: [
    {
      type: "autogenerated",
      dirName: "library",
    },
  ],
};

export default sidebars;
